--[[
  PizzaShackAPI
 
  This is a RESTFul API for Pizza Shack online pizza delivery store. 
 
  OpenAPI spec version: 1.0.0
  Contact: architecture@pizzashack.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

--[[
Unit tests for swagger-client.api.default_api
Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
Please update as you see appropriate
]]
describe("default_api", function()
  local swagger-client_default_api = require "swagger-client.api.default_api"
  -- unit tests for menu_get
  describe("menu_get test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for order_order_id_delete
  describe("order_order_id_delete test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for order_order_id_get
  describe("order_order_id_get test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for order_order_id_put
  describe("order_order_id_put test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for order_post
  describe("order_post test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
