--[[
  PizzaShackAPI
 
  This is a RESTFul API for Pizza Shack online pizza delivery store. 
 
  OpenAPI spec version: 1.0.0
  Contact: architecture@pizzashack.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- error class
local error = {}
local error_mt = {
	__name = "error";
	__index = error;
}

local function cast_error(t)
	return setmetatable(t, error_mt)
end

local function new_error(message, error, description, code, more_info)
	return cast_error({
		["message"] = message;
		["error"] = error;
		["description"] = description;
		["code"] = code;
		["moreInfo"] = more_info;
	})
end

return {
	cast = cast_error;
	new = new_error;
}
