--[[
  PizzaShackAPI
 
  This is a RESTFul API for Pizza Shack online pizza delivery store. 
 
  OpenAPI spec version: 1.0.0
  Contact: architecture@pizzashack.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- menu_item class
local menu_item = {}
local menu_item_mt = {
	__name = "menu_item";
	__index = menu_item;
}

local function cast_menu_item(t)
	return setmetatable(t, menu_item_mt)
end

local function new_menu_item(price, description, name, image)
	return cast_menu_item({
		["price"] = price;
		["description"] = description;
		["name"] = name;
		["image"] = image;
	})
end

return {
	cast = cast_menu_item;
	new = new_menu_item;
}
