--[[
  PizzaShackAPI
 
  This is a RESTFul API for Pizza Shack online pizza delivery store. 
 
  OpenAPI spec version: 1.0.0
  Contact: architecture@pizzashack.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- order class
local order = {}
local order_mt = {
	__name = "order";
	__index = order;
}

local function cast_order(t)
	return setmetatable(t, order_mt)
end

local function new_order(customer_name, delivered, address, pizza_type, credit_card_number, quantity, order_id)
	return cast_order({
		["customerName"] = customer_name;
		["delivered"] = delivered;
		["address"] = address;
		["pizzaType"] = pizza_type;
		["creditCardNumber"] = credit_card_number;
		["quantity"] = quantity;
		["orderId"] = order_id;
	})
end

return {
	cast = cast_order;
	new = new_order;
}
